//
// Created by yogo on 18-9-26.
//

#ifndef PEOPLEDETECTIONTEST_NET_CONSTANT_H
#define PEOPLEDETECTIONTEST_NET_CONSTANT_H


constexpr static unsigned int MAX_LAYER_COUNT = 128;

#define EIGEN

#endif //PEOPLEDETECTIONTEST_NET_CONSTANT_H
